
ALTER TABLE public.ai_extractions
  ADD COLUMN IF NOT EXISTS progress INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS chunks_processed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chunks_total INTEGER,
  ADD COLUMN IF NOT EXISTS partial_results JSONB;
