ALTER TABLE public.ocr_results
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'completed',
  ADD COLUMN IF NOT EXISTS progress INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS pages_processed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pages_total INTEGER,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_ocr_results_status ON public.ocr_results(status);